version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

issues:
  max-same-issues: 0
